// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLamRLHLT3Q9GzEOPoEYdfj5i0b0-Axss',
    appId: '1:9792198179:web:a45817065500e925fd8396',
    messagingSenderId: '9792198179',
    projectId: 'messageapp-2bed6',
    authDomain: 'messageapp-2bed6.firebaseapp.com',
    storageBucket: 'messageapp-2bed6.appspot.com',
    measurementId: 'G-V6JES12F9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHL28hVn5JN9wHnyyvhlsjlcTMbDdndxk',
    appId: '1:9792198179:android:05cb5b1debb1dcdafd8396',
    messagingSenderId: '9792198179',
    projectId: 'messageapp-2bed6',
    storageBucket: 'messageapp-2bed6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY3F55iHgreTvctsN1yAyIjPP0lqVC2Eo',
    appId: '1:9792198179:ios:8006ef090335562efd8396',
    messagingSenderId: '9792198179',
    projectId: 'messageapp-2bed6',
    storageBucket: 'messageapp-2bed6.appspot.com',
    iosBundleId: 'com.example.messageaoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY3F55iHgreTvctsN1yAyIjPP0lqVC2Eo',
    appId: '1:9792198179:ios:8006ef090335562efd8396',
    messagingSenderId: '9792198179',
    projectId: 'messageapp-2bed6',
    storageBucket: 'messageapp-2bed6.appspot.com',
    iosBundleId: 'com.example.messageaoo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLamRLHLT3Q9GzEOPoEYdfj5i0b0-Axss',
    appId: '1:9792198179:web:a7b067344c75c083fd8396',
    messagingSenderId: '9792198179',
    projectId: 'messageapp-2bed6',
    authDomain: 'messageapp-2bed6.firebaseapp.com',
    storageBucket: 'messageapp-2bed6.appspot.com',
    measurementId: 'G-60JED5736T',
  );
}
